name: merge-test

on: 
    pull_request_target:
        types:
          - closed
          
permissions:
  contents: write

jobs:
    build:
        if : github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        env: 
            GITHUB_REF: ${{ github.ref }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            
            - name: Determine Docker final tag
              run: |
                
                if [[ "$GITHUB_REF" == "refs/heads/multitenant-develop" ]]; then
                    FINAL_TAG="merging-to-develop"
                elif [[ "$GITHUB_REF" == "refs/heads/multitenant" ]]; then
                    FINAL_TAG="merging-to-main"
                else
                    FINAL_TAG="else"
                fi
                echo "Docker final tab: $FINAL_TAG"
            - name: Create GitHub TAG
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git tag -a 0.0.1 -m "Release version 0.0.1"
                git push origin 0.0.1